#include "english_assistance/ui/xpm.h"

namespace english_assistance {
    namespace xpm {
        const char *APP_ICON[] = {
            "50 50 58 1 ",
            "  c None",
            ". c black",
            "X c #500000",
            "o c #7B0000",
            "O c #8F0000",
            "+ c #900000",
            "@ c #930100",
            "# c #9C0000",
            "$ c #9D0000",
            "% c #AB0000",
            "& c #B10000",
            "* c #E10000",
            "= c #E20000",
            "- c #E90000",
            "; c #ED0000",
            ": c #EC0100",
            "> c #FE0000",
            ", c red",
            "< c #FE0100",
            "1 c #FF0100",
            "2 c #FD0200",
            "3 c #FD0300",
            "4 c #FE0200",
            "5 c #FB0400",
            "6 c #F80700",
            "7 c #F90700",
            "8 c #FC0400",
            "9 c #FC0500",
            "0 c #F70C00",
            "q c #FA0800",
            "w c #F41000",
            "e c #F01400",
            "r c #DB3300",
            "t c #DC3300",
            "y c #E92000",
            "u c #BF5C00",
            "i c #B56600",
            "p c #BA6300",
            "a c #B66900",
            "s c #B56A00",
            "d c #AF7200",
            "f c #A97B00",
            "g c #C85000",
            "h c #70CC00",
            "j c #65DC00",
            "k c #44FF00",
            "l c #46FF00",
            "z c #47FF00",
            "x c #4AFF00",
            "c c #4BFF00",
            "v c #4CFF00",
            "b c #9C8E00",
            "n c #939800",
            "m c #949900",
            "M c #A38400",
            "N c #8CA500",
            "B c #82B100",
            "V c #83B100",
            "                                                  ",
            "                                                  ",
            "                                                  ",
            "                                                  ",
            "                                                  ",
            "                                                  ",
            "                                                  ",
            "                                vvk               ",
            "                               vvvcc              ",
            "                              nvvvvvvk            ",
            "                             <<mvvvvvvk           ",
            "                             <<<hvvvvvv           ",
            "                            <<<<<tjvvvvv          ",
            "                           <<<<<<<yccvvvk         ",
            "                          <<<<<<<<<Mkvvvv         ",
            "                         <<<<<<<<<<<pcvvv         ",
            "                        <<<<<<<<<<<<<ivvvc        ",
            "                       <<<<7<<<<<<<<<<cvvv        ",
            "                      <<<<<<<<<<<<<<<tvvvv        ",
            "                      <<<<<<<<<<<<<<<<cvvvc       ",
            "                     <<<<<<<<<<<<<<<<<avvvc       ",
            "                    <<<<<<;+;<<<<<<<<<<vvvc       ",
            "                   <<<<<<<O.O<<<<<<<<<<vvvv       ",
            "                  <<<<<<<<;+;<<0<<<<<<<vvvv       ",
            "                 <<<<<<<<<<<<<<<<<<<<<7cvvv       ",
            "                <<<<<<<<<<<<<<<<<<<<<<Vcvcc       ",
            "               <<<<;+;<<<<<<<-<<<<<<<fccvvc       ",
            "              <<<<<O.+<<<<<<&@<<<<<<<vccvv        ",
            "             <<<<<<;+;<<<<<=X<<<<<<<Nvvvvv        ",
            "            <<<<<<<<<<<<<<$o<<<<<<<<vvvvvv        ",
            "           <<<<<<<<<<<<<%$=<<<<<<<<<vvcvv         ",
            "          <<<<<<<<<<<<<<<<<<<<<<<<<mvccvv         ",
            "          <<<<<<<<<<<<<<<<<<<<<<<<<vvvvvv         ",
            "         <<<<<<<<<<7<<<<<<<<<<<<<<bvvvvc          ",
            "        0<<<<<<<<<<<<<<<<<<<<<<<<pvvvvvk          ",
            "       vg7<<<<<<<<<<<<<<<<<<<<<<gvvvvvv           ",
            "       v<<<<<<<<<<<<<<<<<<<<<<<avvvvvc            ",
            "      vvf<<<<<<<<<<<<<<<<<<<<ejvvvvvv             ",
            "      vvvj<<<<<<<<<<<<<<<<<<Mvvvvvvvc             ",
            "      vvvvV<<<<<<<<<<<<<<qVvvvvvvvvc              ",
            "      vvvvvV7<<<<<<<<<8Nvvvvvvvvvvc               ",
            "      vvvvvvvvd<<<<<<Mvvvvvvvvvvv                 ",
            "       vvvvvvvvvvvvvvvvvvvvvvvvk                  ",
            "        cvvvvvvvvvvvvvvvvvvvkc                    ",
            "          vvvvvvvvvvvvvvv                         ",
            "             vvvvc  vv                            ",
            "                                                  ",
            "                                                  ",
            "                                                  ",
            "                                                  "
        };
    }
}
